services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/ncmpassword
    volumes:
      - neo4j_data:/data
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
volumes:
  neo4j_data:
